In [21]:
import pyodbc
import snowflake.connector

In [22]:
sql_server_connection_string = 'DRIVER={SQL Server};SERVER=DESKTOP-KRL9TCA;DATABASE=demoDB;Trusted_Connection=yes'
sql_server_conn = pyodbc.connect(sql_server_connection_string)
sql_server_cursor = sql_server_conn.cursor()
sql_server_cursor

In [23]:
import snowflake.connector
from datetime import datetime

# Connect to Snowflake
snowflake_connection = snowflake.connector.connect(
    user='BHARATHIRAJA',
    password='Bharathi472$',
    account='zszomie-ak85849',
    warehouse='COMPUTE_WH',
    database='SKILL_MATRIX',
    schema='public'
)

# Create a cursor
snowflake_cursor = snowflake_connection.cursor()

try:
    # Define the SQL statement to create the table if it doesn't exist
    create_table_sql = '''
    CREATE TABLE IF NOT EXISTS Users (
        id VARCHAR(36),
        email VARCHAR(255),
        password VARCHAR(255),
        username VARCHAR(255),
        address VARCHAR(255),
        phone VARCHAR(20),
        role VARCHAR(50),
        designation VARCHAR(50),
        created_at DATE -- Change to DATE format
    )
    '''

    # Execute the SQL statement to create the table
    snowflake_cursor.execute(create_table_sql)

    # Retrieve data from SQL Server
    sql_query = 'SELECT * FROM Users'
    sql_server_cursor.execute(sql_query)
    data_to_transfer = sql_server_cursor.fetchall()

    # Define the Snowflake SQL statement with named placeholders
    snowflake_query = '''
    INSERT INTO Users (id, email, password, username, address, phone, role, designation, created_at)
    VALUES (%(id)s, %(email)s, %(password)s, %(username)s, %(address)s, %(phone)s, %(role)s, %(designation)s, %(created_at)s)
    '''

    # Convert the list of tuples into a list of dictionaries
    data_dicts = []
    for row in data_to_transfer:
        # Convert created_at to date format
        created_at_date = datetime.strptime(row[8], '%m-%d-%Y').date()
        data_dict = {
            'id': row[0],
            'email': row[3],
            'password': row[2],
            'username': row[1],
            'address': row[4],
            'phone': row[5],
            'role': row[6],
            'designation': row[7],
            'created_at': created_at_date
        }
        data_dicts.append(data_dict)

    # Execute the Snowflake query with named placeholders and list of dictionaries
    snowflake_cursor.executemany(snowflake_query, data_dicts)

    # Commit the transaction
    snowflake_connection.commit()
    
    print("Data transfer successful!")

except snowflake.connector.errors.DatabaseError as db_error:
    print("Snowflake Database Error:", db_error)

except Exception as e:
    print("An error occurred:", e)

finally:
    # Close Snowflake cursor and connection
    snowflake_cursor.close()
    snowflake_connection.close()
sql_query = 'SELECT * FROM Skills'
sql_server_cursor.execute(sql_query)
data_to_transfer = sql_server_cursor.fetchall()

create_table_sql = '''
CREATE TABLE IF NOT EXISTS Skills (
    id VARCHAR(255),
    user_id VARCHAR(255),
    skillname VARCHAR(255),
    proficiencylevel VARCHAR(255),
    status VARCHAR(255),
    createdat TIMESTAMP
)
'''

# Execute the SQL statement to create the table in Snowflake
snowflake_cursor.execute(create_table_sql)

# Convert the list of tuples into a list of dictionaries suitable for Snowflake
data_dicts = []
for row in data_to_transfer:
    data_dict = {
        'id': row[0],
        'user_id': row[1],
        'skillname': row[2],
        'proficiencylevel': row[3],
        'status': row[4],
        'createdat': row[5]
    }
    data_dicts.append(data_dict)

# Define the Snowflake SQL statement with named placeholders for insertion
snowflake_insert_query = '''
INSERT INTO Skills (id, user_id, skillname, proficiencylevel, status, createdat)
VALUES (%(id)s, %(user_id)s, %(skillname)s, %(proficiencylevel)s, %(status)s, %(createdat)s)
'''

# Execute the Snowflake query to insert the data
snowflake_cursor.executemany(snowflake_insert_query, data_dicts)

# Commit the transaction in Snowflake
snowflake_connection.commit()

# Close the Snowflake cursor and connection
snowflake_cursor.close()
snowflake_connection.close()

In [24]:

create_table_sql = '''
CREATE TABLE IF NOT EXISTS Project (
    id VARCHAR(36),
    user_id VARCHAR(36),
    skill_id VARCHAR(36),
    projectname VARCHAR(255),
    projectdescription VARCHAR(255),
    projectexperience VARCHAR(50),
    role VARCHAR(50),
    status VARCHAR(50),
    created_at TIMESTAMP
)
'''
snowflake_cursor.execute(create_table_sql)


# Retrieve data from SQL Server
sql_query = 'SELECT * FROM Projects'
sql_server_cursor.execute(sql_query)
data_to_transfer = sql_server_cursor.fetchall()

# Define the Snowflake SQL statement with named placeholders
snowflake_query = '''
INSERT INTO Project (id, user_id, skill_id, projectname, projectdescription, projectexperience, role, status, created_at)
VALUES (%(id)s, %(user_id)s, %(skill_id)s, %(projectname)s, %(projectdescription)s, %(projectexperience)s, %(role)s, %(status)s, %(created_at)s)
'''

# Convert the list of tuples into a list of dictionaries
data_dicts = []
for row in data_to_transfer:
    data_dict = {
        'id': row[0],
        'user_id': row[1],
        'skill_id': row[2],
        'projectname': row[3],
        'projectdescription': row[4],
        'projectexperience': row[5],
        'role': row[6],
        'status': row[8],
        'created_at': row[7]
    }
    data_dicts.append(data_dict)

# Insert data into the "Project" table in Snowflake
snowflake_cursor.executemany(snowflake_query, data_dicts)
snowflake_connection.commit()

# Close connections
snowflake_cursor.close()
snowflake_connection.close()
sql_server_cursor.close()

In [27]:

create_table_sql = '''
CREATE TABLE IF NOT EXISTS Certification (
    id VARCHAR(36),
    user_id VARCHAR(36),
    skill_id VARCHAR(36),
    certificationname VARCHAR(255),
    certificationfile VARCHAR(255),
    issueddate DATE,
    expirydate DATE,
    status VARCHAR(50),
    created_at TIMESTAMP
)
'''
snowflake_cursor.execute(create_table_sql)

# Retrieve data from SQL Server
sql_query = 'SELECT * FROM Certifications'
sql_server_cursor.execute(sql_query)
data_to_transfer = sql_server_cursor.fetchall()

# Define the Snowflake SQL statement with named placeholders
snowflake_query = '''
INSERT INTO Certification (id, user_id, skill_id, certificationname, certificationfile, issueddate, expirydate, status, created_at)
VALUES (%(id)s, %(user_id)s, %(skill_id)s, %(certificationname)s, %(certificationfile)s, %(issueddate)s, %(expirydate)s, %(status)s, %(created_at)s)
'''

# Convert the list of tuples into a list of dictionaries
data_dicts = []
for row in data_to_transfer:
    data_dict = {
        'id': row[0],
        'user_id': row[1],
        'skill_id': row[2],
        'certificationname': row[3],
        'certificationfile': row[4],
        'issueddate': row[5],
        'expirydate': row[6],
        'status': row[8],
        'created_at': row[7]
    }
    data_dicts.append(data_dict)

# Insert data into the "Certification" table in Snowflake
snowflake_cursor.executemany(snowflake_query, data_dicts)
snowflake_connection.commit()

# Close connections
snowflake_cursor.close()
snowflake_connection.close()
sql_server_cursor.close()

NameError: name 'sql_server_connection' is not defined